### ISSUE TITLE
Locale date has not been initialized when  use24HourFormat set to  false

### ISSUE THREAD

**Issue by AniketDhanak** [m3uzz/date_time_picker#69]
```
 [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LocaleDataException: Locale data has not been initialized, call initializeDateFormatting(<locale>).
E/flutter ( 4297): #0      UninitializedLocaleData._throwException (package:intl/src/intl_helpers.dart:80:5)
E/flutter ( 4297): #1      UninitializedLocaleData.containsKey (package:intl/src/intl_helpers.dart:74:7)
E/flutter ( 4297): #2      DateFormat.localeExists (package:intl/src/intl/date_format.dart:834:28)
E/flutter ( 4297): #3      verifiedLocale (package:intl/src/intl_helpers.dart:159:19)
E/flutter ( 4297): #4      new DateFormat (package:intl/src/intl/date_format.dart:266:27)
E/flutter ( 4297): #5      _DateTimePickerState.set12HourTimeValues (package:date_time_picker/date_time_picker.dart:763:20)
E/flutter ( 4297): #6      _DateTimePickerState._showDateTimePickerDialog (package:date_time_picker/date_time_picker.dart:876:11)
E/flutter ( 4297): <asynchronous suspension>
E/flutter ( 4297): 

```
It is only coming for use24HourFormat: true,
If it is set to false it doesn't throw error

**Comment by Awesomeplayer165** [comment]
I also have this problem. Is there any update on this?

I tried calling `initializeDateFormatting()` myself but to no avail

**Comment by saurabhmore** [comment]
Facing the same issue needed 12hr format with locale support.
Is this issue fixed??
